#!/usr/bin/env bash

cd ~/.jbw/arch

source bin/workstation_install
source bin/graphics

echo
echo "Install DMS"
echo

sudo -v && curl -fsSL https://install.danklinux.com | sh -s -- \
  -c hyprland -t ghostty --dms-greeter --danksearch -y

sudo pacman -S --needed \
  acl \
  cava \
  kimageformats \
  nautilus \
  power-profiles-daemon \
  uwsm

dms-greeter enable
