#!/usr/bin/env bash

cd ~/.jbw/arch

source bin/graphics
source bin/basic_workstation	# Packages common to all installs
source bin/pandoc_pip
source bin/pdf_scan
source bin/vlc
source bin/kdenlive
source bin/vscodium
source bin/gameing
source bin/dms_configs
source bin/dms

reboot
